---
title: "Test Document"
author: "Osvaldo Cervantes"
date: "12/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstanarm)
library(gt)
library(gtsummary)
library(broom.mixed)
library(rgdal)
library(leaflet)
library(tigris)
```

```{r}

graph <- anxiety %>%
  ggplot(aes(x = game)) +
  geom_bar()


stan_glm(data = anxiety, 
         hours ~ gender + gade, 
         family = gaussian, 
         refresh = 0)

test <- anxiety %>%
  filter(gender == "Female")

```

```{r}

anxiety %>%
  ggplot(aes(x = gade, y = hours)) +
  geom_col() +
  labs(title = "Number of Hours by GAD Effects on Work", 
       x = "Self-Reported Impact of Anxiety on Workplace Performance", 
       y = "Hours")

anxiety %>%
  group_by(gad_t) %>%
  mutate(avg_hours = mean(hours)) %>%
  ggplot(aes(x = gad_t, y = avg_hours)) +
  geom_point() +
  labs(title = "Average Hours Spent Gaming by Anxiety Score", 
       x = "Score on GAD Scale", y = "Average Hours Played")

```

```{r}

fit_model <- stan_glm(data = anxiety, 
         hours ~ gender + gade + gad_t, 
         family = gaussian, 
         refresh = 0)

tbl_regression(fit_model) %>%
  as_gt() %>%
  tab_header(title = "Regression of Hours Spent Gaming", 
             subtitle = "The Link Between Hours Played, Gender, and 
             Anxiety") %>%
  tab_source_note("Source: Study Published by Marian Sauter and Dejan 
                  Draschkow")

```


```{r}

fit_1 <- stan_glm(data = overwatch, 
         choice_dictation ~ neuroticism + conscienctiousness + agreeableness, 
         family = gaussian(), 
         refresh = 0)

tbl_regression(fit_1, intercept = TRUE) %>%
  as_gt() %>%
  tab_header(title = "Regression of Character Choice in Overwatch", 
             subtitle = "The Link Between Character Choices and Differing 
             Behavioral Characteristics") %>%
  tab_source_note("Source: 'Character choice in online gaming' by Duncan Hodges 
                  and Oliver Buckley")
  

```

```{r}

nations <- anxiety %>%
  count(residence)

```

```{r}

countries <- readOGR("raw_data/nations", "ne_50m_admin_0_countries")

gad_total <- anxiety %>%
  group_by(residence) %>%
  summarize(gad_t = sum(gad_t)) %>%
  gad_total$residence[gad_total$residence == "USA"] <- "United States of America"

joined_dataset <- geo_join(countries, gad_total, "ADMIN", "residence")

leaflet() %>% 
  addTiles() %>% 
  addPolygons(data = joined_dataset, fillColor = joined_dataset$residence)

```

```{r}


gad_total$residence[gad_total$residence == "USA"] <- "United States of America"

gad_total$residence[gad_total$residence == "UK"] <- "United Kingdom"

countries

joined_dataset

```

